dexidp/website

Makefile
config.toml
netlify.toml

98% sure the linkchecker is causing builds to fail. We can re-add this at a later date, for now let's get the thing working.

Update default values, remove linkchecker

---

content/docs/proposals/_index.md
content/docs/proposals/token-revocation.md
content/docs/proposals/upstream-refreshing.md
content/docs/proposals/user-object.md

Setting proposals documents to draft as per conversation in issue https://github.com/dexidp/website/issues/20

Setting proposals documents to draft

---

config.toml
layouts/partials/social-buttons.html

Updating twitter button in social-buttons partial, as well as updating the url in the config.toml
Fixes https://github.com/dexidp/website/issues/33, thx for the info @justaugustus!

Updating twitter button

---

config.toml

fixes https://github.com/dexidp/website/issues/32

removing CNCF link from header

---

content/docs/api.md
content/docs/getting-started.md
content/docs/oidc-certification-setup.md
content/docs/using-dex.md

Update links from website to API and examples

---

config.toml
layouts/index.html
layouts/partials/footer.html
layouts/partials/home/cncf-status.html

Fixes items 6 & 7 of https://github.com/dexidp/website/issues/22
Updating footer
- copyright for Dex IdP contriubters
- copyright for Linux Foundation
Home page updates:
- CNCF project status
- logo
- link to upcoming KubeCon + CloudNativeCon

Updating footer & bottom of home page

---

content/docs/_index.md

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

Remove broken links after adding "Development" section

---

content/docs/connectors/oidc.md

Fix broken link (docs were moved)

---

layouts/partials/home/cncf-status.html

Tiny change: just giving the logo some room to breathe.

updating cncf-status.html

---

layouts/partials/social-buttons.html

Giving logos room to breathe
fixes: https://github.com/dexidp/website/issues/70

updating social-buttons.html

---

content/docs/getting-started.md
content/docs/id-tokens.md

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

chore: fix using dex link

---

content/_index.md

Replica of https://github.com/dexidp/dex/pull/2089

chore: remove go dev badge from the title screen

---

content/docs/connectors/microsoft.md

Signed-off-by: Maik <maik.brauer@vodafone.com>

Added documentation about emailToLowercase

---

content/docs/connectors/_index.md
content/docs/connectors/keystone.md

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
Fixes #89

Keystone connector documentation

---

content/docs/templates.md

Improve web asset docs

---

content/docs/id-tokens.md

Documentation for https://github.com/dexidp/dex/pull/1846

Refresh token rotation documentation

---

content/docs/development/integration-tests.md

Related https://github.com/dexidp/dex/pull/2091

feat: Kubernetes storage integration tests doc

---

content/docs/connectors/oidc.md

Removed from this connector in https://github.com/dexidp/dex/pull/2511
Signed-off-by: Anthony Brandelli <abrandel@cisco.com>

Remove docs for OIDC connector mentioning hosted domains claim

---

content/docs/id-tokens.md

issue: #115 
validForIfNotUsed is not mentioned anywhere in the dex code itself.

Fix validIfNotUsedFor parameter name

---

content/_index.md

Currently broken due to badges/shields#8671

Fix index CI badge

---

content/docs/connectors/oauth.md

typo in connectors/oauth.md
Signed-off-by: Makariy <70059595+ya-makariy@users.noreply.github.com>

Authentication Through an OAuth 2.0 Provider: typo in config sample

---

content/docs/kubernetes.md

Few more references are stale. updated them.  like #130

Update kubernetes.md reference to docs

---

content/docs/connectors/gitea.md

docs(gitea): update the new OAuth link.

---

content/docs/connectors/local.md

Adds documentation for the local connector

feat: add documentation for local connector

---

layouts/partials/footer.html

Restyle footer

---

content/docs/connectors/oidc.md

Update the doc after merging https://github.com/dexidp/dex/pull/3267

Override OIDC provider discovered claims

---

content/docs/connectors/gitlab.md

https://github.com/dexidp/dex/pull/2941

Add descride for GetGroupsPermission flag in Gitlab connector
