layouts/partials/section-nav.html

Using .LinkTitle will use markdown front matter "linkTitle" before "title"
fixes #27

Updating section-nav.html

---

layouts/partials/github-edit.html

correcting editUrl to include /blob/main for editing on GitHub

---

content/_index.md

Correcting links that 404 on the front page.
Fixes https://github.com/dexidp/website/issues/25.
More discussion may be needed for https://github.com/dexidp/website/issues/26.

correcting links on the front page

---

content/docs/connectors/bitbucketcloud.md

It became mandatory to give Bitbucket OAuth consumer access to read workspace membership for getting user's teams.

Update BitbucketCloud OAuth2 consumer required permissions

---

content/docs/connectors/saml.md

Add a warning to indicate that this connector is unmaintained and likely
vulnerable to auth bypasses.
Regardless of the decision to deprecate the connector, I think this is
important to communicate to potential users.
https://github.com/dexidp/dex/discussions/1884

connectors: add warning to the SAML connector

---

content/docs/getting-started.md

This PR fixes some issues with "Getting Started" documentation (that were mentioned in #78).

fix: refresh getting started documentation

---

content/docs/connectors/openshift.md

'/' is not allowed as part of an annotation name; ecape character is '~1' for '/' in kubernetes due to:
https://github.com/kubernetes/kubernetes/issues/26890
https://tools.ietf.org/html/rfc6901#section-4

Fix syntax error in openshift connector doc

---

content/docs/getting-started.md

Running `make` executed silently without any `bin` folder being generated on a fresh Ubuntu installation.

Update build instruction

---

content/docs/id-tokens.md

Fix a typo in section `expiry`.
On text was `expire` looking at code (https://github.com/dexidp/dex/blob/716eef83bca805e1607338fe0a271affc2d097b0/cmd/dex/config.go#L31) we see `expiry`
Others changes in text is blank space on end of line.

[ID Tokens] Fix typo in section name

---

content/docs/kubernetes.md

Example file `dex.yml` is expecting namespace `dex` but all example
commands aren't using this namespace so dex won't be able to find
secrets.

add namespace in kubectl commands

---

content/docs/connectors/authproxy.md

Update authproxy documentation with configurable headers and staticGroups.
See : https://github.com/dexidp/dex/pull/2371

[authproxy] add cusom header and group configuration documentation

---

content/docs/connectors/_index.md
content/docs/connectors/oauth.md

this is the doc for generic oauth 2.0 connector that PR in https://github.com/dexidp/dex/pull/1630

add docs for generic oauth 2.0 connector

---

content/docs/connectors/oidc.md

This caveat seems to be stale. It references https://github.com/dexidp/dex/issues/863, which was closed in https://github.com/dexidp/dex/pull/1180. Looking at the PR this does seem to propagate the upstream claims downstream on refresh, and in my (albeit limited) testing changed claims do come down in the dex ID token. 
Possible I'm incorrect here, but as far as I can see this is just a doc bug and the actual functionality has been there for a while. 
Signed-off-by: Anthony Brandelli <abrandel@cisco.com>

Remove stale caveat that indicates changed upstream claims won't be sent downstream from dex

---

content/docs/connectors/oidc.md

Hi,
This PR adds the description for the new config field `acrValues`
the original issue is here -> https://github.com/dexidp/dex/issues/2417
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

docs: Add acr_values field description into the docs

---

content/docs/connectors/ldap.md

The `-h` option of ldapsearch was [deprecated](https://www.openldap.org/software/man.cgi?query=ldapsearch&apropos=0&sektion=1&manpath=OpenLDAP+2.0-Release&arch=default&format=html) in favor of `-H` since OpenLDAP 2.0 (which was [released](https://en.wikipedia.org/wiki/OpenLDAP#Release_summary) in August 2000, a long long time ago), and is [removed](https://www.openldap.org/doc/admin25/appendix-upgrading.html#Client%20utility%20changes)  since version 2.5. 
So we should use `-H` instead.

Fix using ldapsearch deprecated -h option in ldap.md

---

content/docs/connectors/ldap.md

Currently this field can only be found by reading the source code @nabokihms

📃 docs(LDAP):  Add preferredUsernameAttr field for LDAP

---

content/docs/getting-started.md

Fixes https://github.com/dexidp/dex/issues/2749
Signed-off-by: Gabriele Quaresima <gabriele.wolfox@gmail.com>

fix: set minimum go version requirement to 1.19

---

content/docs/id-tokens.md
content/docs/kubernetes.md
content/docs/using-dex.md

The page has moved to the new link:
- updated all the references to new link. (since the content also have not changed , just the content was moved to different URL).

Update Reference link to openid-connect-tokens for api-server authentication

---

content/docs/connectors/google.md

We tested this, and a user with the `Groups Reader (BETA)` Role assigned works fine.
Signed-off-by: Ciaran Moran <ciaran@weave.works>

Google Workspace user only needs Groups Reader

---

content/docs/getting-started.md

Mention container images, and configuration templating
related #78 #102 dexidp/dex#2915

update getting started

---

content/docs/getting-started.md

fixes a link, that would resolve to https://dexidp.io/docs/getting-started/charts.dexidp.io otherwise

fix external URL in getting-started.md

---

content/docs/connectors/google.md

Removes a deprecated option for using google SA and uses the current option instead.
Resolves https://github.com/dexidp/website/issues/150

fix: update deprecated reference for using google SA

---

content/docs/tokens.md

Adds two missing options to the expiration settings. 
I also renamed the page because it doesn't just cover ID Tokens.

fix: add missing options for expiry settings

---

content/docs/connectors/microsoft.md

The current documentation for getting groups from Azure in the Microsoft connector makes it seem like any valid `tenant` configuration is enough to get groups from Azure. This is however not the case, as Dex specifically checks if `tenant` is not set to `common`, `consumers` or `organizations` (as seen here: https://github.com/dexidp/dex/blob/295b0acd61055b5e17a1b1c74908a0c723a62a17/connector/microsoft/microsoft.go#L132).
If a user has for example configured `groups` in their connector after reading the documentation, then they would expect to get groups out when authenticating via Dex. However if `tenant` has not been set to either `<tenant uuid>` or `<tenant name>`, then the groups lookup will not happen. And neither the docs nor the Dex containers' own logs make any mention of this. …

Fix misleading section in Microsoft connector

---

content/docs/connectors/google.md

This documentation update is intended to capture the important changes made in Pull Requests [#2989](https://github.com/dexidp/dex/pull/2989) and [#2911](https://github.com/dexidp/dex/pull/2911). Both PRs brought notable enhancements to the Dex project and it's essential to ensure our documentation reflects these updates.

adjust documentation according to pr's 

---

content/docs/connectors/oauth.md

Fixes following error:
```
error parse config file /tmp/dex.yaml: error unmarshaling JSON: parse connector config: json: cannot unmarshal string into Go struct field Config.rootCAs of type []string
```

Fix type of field rootCAs in connector oauth

---

content/docs/oauth2.md

Adds documentation for the oauth2 settings with focus on different auth flows.
Resolves https://github.com/dexidp/website/issues/144
Resolves https://github.com/dexidp/website/issues/79

feat: cover missing oauth2 settings

---

content/docs/_index.md

Original link was still pointing to CoreOS.

Update link to security disclosure policy

---

content/docs/custom-scopes-claims-clients.md

https://github.com/dexidp/dex/blob/ed920dc27ad79c3593037ad658552e8e80bab928/cmd/dex/serve.go#L207
This functionality was never documented. Lmk if you'd like to see it somewhere else.

FIX: document secretEnv on oidc config to inject oidc secret env vars

---

content/docs/connectors/microsoft.md

Adds a description and example usage for using the `domainHint` configuration parameter added in PR https://github.com/dexidp/dex/pull/2586
This enhancement was added to address issue https://github.com/dexidp/dex/issues/2585

Microsoft Connector: domainHint configuration parameter

---

content/docs/connectors/google.md

Update Google connector docs to include `promptType` configuration documentation.
Ref: 
https://github.com/dexidp/dex/pull/3475
https://github.com/dexidp/dex/issues/3450

docs: Update Google connector doc to include promptType config

---

content/docs/connectors/github.md

The GitHub connector docs were very hard to read before, and did not include any reference to the very important `preferredEmailDomain` feature added by https://github.com/dexidp/dex/pull/2740

Update the GitHub connector docs
